### PR TITLE
Use copysign

### PR DESCRIPTION
**Pull request by dpsanders**

### CODE REVIEW

**Comment by JeffreySarnoff** [comment]
the problem is in the rewrite of the tests -- if you deal with that, I will put this through and check timings later

**Comment by dpsanders** [comment]
Tests are now passing @JeffreySarnoff.

**Comment by dpsanders** [comment]
Thanks! Could you tag a new release, please?

**Comment by dpsanders** [comment]
Thanks! Could you tag a new release, please?

On 1 Jun 2017 2:36 p.m., "Jeffrey Sarnoff" <notifications@github.com> wrote:

Merged #7 <https://github.com/JeffreySarnoff/AdjacentFloats.jl/pull/7>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JeffreySarnoff/AdjacentFloats.jl/pull/7#event-1106051030>,
or mute the thread

**Comment by JeffreySarnoff** [comment]
done (in their ballpark)

**Comment by dpsanders** [comment]
Thanks!

**Pull request merged**
